---
- name: Ensure dependencies are installed.
  apt:
    pkg: curl
    state: installed

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  register: jenkins_download
  when: jenkins_version is defined

- name: Install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  when: jenkins_download.changed
  ignore_errors: True
  failed_when: False
  notify: configure default users

- name: Validate Jenkins is installed and register package name.
  apt:
    name: jenkins
    state: present
  notify: configure default users

- name: Install Jenkins from repository.
  apt:
    name: jenkins
    state: installed
  when: jenkins_version is undefined
